### ISSUE TITLE
Repairing git repo

### ISSUE THREAD

**Issue by susmateusz** [rkarwack/pogoda#1]
IMO /.idea/ should be in .gitignore. And you doesn't have any .gitignorefile. Please repair it.

**Comment by susmateusz** [comment]
Everytime you build project files in /.idea/ change. So every commit notes is unreadable (for example: https://github.com/rkarwack/pogoda/commit/5683ee48c19350fa70a3e83e781b139aef401443 ).

**Comment by rkarwack** [comment]
.gitignore added
